language: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g serverless
  - cd service
  - npm install
  - sls deploy
  - cd ..
script:
  - npm test