service:
  name: rocketeer-node-usage-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  basic:
    handler: functions/basic.handler
    events:
      - http:
          method: get
          path: basic
  withApiKey:
    handler: functions/withApiKey.handler
    events:
      - http:
          method: get
          path: protected
