service:
  name: rocketeer-node-usage-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: functions/basic.handler
    events:
      - http:
          method: get
          path: basic
